import csv
from pathlib import Path
# Edit these values manually based on the columns produced by extraction.py.
# Supported rule keys: min, max, equals, not_equals, in.
FILTERS = {
    "years_of_experience": {"min": 3},
    "profile_completeness_score": {"min": 50},
}

def _default_output_path(input_path):
    path = Path(input_path)
    return path.with_name(f"filtered_{path.name}")

def _coerce_value(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return value

def _matches_rule(value, rule):
    comparable_value = _coerce_value(value)

    if "min" in rule and comparable_value < rule["min"]:
        return False
    if "max" in rule and comparable_value > rule["max"]:
        return False
    if "equals" in rule and comparable_value != rule["equals"]:
        return False
    if "not_equals" in rule and comparable_value == rule["not_equals"]:
        return False
    if "in" in rule and comparable_value not in rule["in"]:
        return False

    return True

def row_matches_filters(row, filters):
    """Return True when a CSV row passes every configured filter."""
    for column, rule in filters.items():
        if column not in row:
            raise ValueError(f"Filter column '{column}' was not found in the CSV.")
        if not _matches_rule(row[column], rule):
            return False

    return True

def filter_data(input_csv, filters=None, output_path=None):
    """
    Filter an extracted candidates CSV and write only passing rows to a new CSV.

    Args:
        input_csv: CSV generated by extraction.py.
        filters: Optional mapping of column name to filter rule. Defaults to FILTERS.
        output_path: Optional output CSV path. Defaults to filtered_<input filename>.

    Returns:
        list of row dictionaries written to the filtered CSV.
    """
    filters = FILTERS if filters is None else filters
    input_path = Path(input_csv)
    output_path = Path(output_path) if output_path else _default_output_path(input_path)

    with open(input_path, "r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        if not reader.fieldnames:
            raise ValueError("Input CSV must include a header row.")

        rows = [row for row in reader if row_matches_filters(row, filters)]

    with open(output_path, "w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=reader.fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    return rows

if __name__ == "__main__":
    extracted_file = "extracted_years_of_experience_profile_completeness_score.csv"
    filter_data(extracted_file)
